### PR TITLE
Personalized search

### LINKED ISSUE #122: [US-16] Search Through User Profiles
Epic: #73 

As a registered user, I want to search through a list of various users and access their user profile pages, so that I can discover other users and read about them.

MoSCoW: M
Business Value:XL
Risk: L

### LINKED ISSUE #170: [US-40-41-V2] Search for a Job
As a registered user, I want to be able to search for job positions by name and apply filters to the search as desired, so that I can view a specified selection of job posts.

Epic Name: #77 Job Search
MoSCoW: M
Business Value:XL
Risk: M

### PR DESCRIPTION
**Pull request by JIAYI615**
This pull request includes the implementation of the following user stories: 

- #170 
- #122 
To test this feature:
  - go to the login page
  - sign in to a valid account
  - enter the search value in the search bar placed in the header
  - click the search button
  - **Expected Result**: The searched user and the searched jobs are displayed on the search screen. The user can select
 job section or user section to check the result. If there's no result matched, the message 'no result for $searchValue' will be displayed. The user should be able to access the user profile page and the job detail page by clicking button 'View profile' and 'View detail' separately. 

For filter:
 - On the search result page, click the button 'Add filter for job search'
 - A filter form should be displayed for the user to enter filter value
 - after filling the form, click apply
 - the searching result should be changed to match the filter value.

If merged, this pull request closes #122, closes #170.

### CODE REVIEW

**Comment by KhaledOwaida** [comment]
I  have tested the functionality and works as intended! Great work!

**Review by VCastelli — CHANGES_REQUESTED** [review]
The search box works well when you type something into the text box and click search. This feature accurately presents the relevant information when searching for a specific person or job. The view detail and view profile buttons also correctly redirect you to the correct job post's details or user's profile. 

For the search filter, however, it doesn't seem to be working as well. When I add elements to filter the search and then click on either apply or save search, the new personalized search doesn't go through. By that, I mean, the searching result does not get changed to match the filter value. I believe there could be a connection issue with the apply search button. Please let me know if there is something I'm doing wrong while testing it. 

Also, small points/details I want to mention: 
- the view detail button would be better labelled as "View Details"
- the placeholder values in the personalized search filter alter between capital letters and lowercase letters; I think it would be best to make those consistent
- What is the difference between the Apply button and the save search button in the personalized search feature?

**Comment by z-bruce** [comment]
> * What is the difference between the Apply button and the save search button in the personalized search feature?

The Apply button should be applying the selected filters to the Search, whereas the Save Search button will (eventually) save the selected filters as a Job Alert (so the user can be notified if jobs matching those filters are posted on the platform).

**Comment by JIAYI615** [comment]
> The search box works well when you type something into the text box and click search. This feature accurately presents the relevant information when searching for a specific person or job. The view detail and view profile buttons also correctly redirect you to the correct job post's details or user's profile.
> 
> For the search filter, however, it doesn't seem to be working as well. When I add elements to filter the search and then click on either apply or save search, the new personalized search doesn't go through. By that, I mean, the searching result does not get changed to match the filter value. I believe there could be a connection issue with the apply search button. Please let me know if there is something I'm doing wrong while testing it.
> 
> Also, small points/details I want to mention:
> 
> * the view detail button would be better labelled as "View Details"
> * the placeholder values in the personalized search filter alter between capital letters and lowercase letters; I think it would be best to make those consistent
> * What is the difference between the Apply button and the save search button in the personalized search feature?

update the code, the displayed message will be changed if there's no result after applying the filter. Apply button is changed to 'Apply Filter' for better clarification, 'View detail' button is changed to 'View details'

**Comment by VCastelli** [comment]
I see that you renamed the buttons and place holders which is great! The search bar still works as intended! 

However, I don't seem to see a feedback message that gets returned to the user if no search results match the personalized filter search. The feedback is displayed accurately for the search bar on its own, but not for the search filter. I.e.: if I try to search for jobs created by Microsoft in the search filter and I press on apply search, the search filter closes and I am shown the output of my last search performed through the search bar rather than the filtered search output.

**Comment by JIAYI615** [comment]
> I see that you renamed the buttons and place holders which is great! The search bar still works as intended!
> 
> However, I don't seem to see a feedback message that gets returned to the user if no search results match the personalized filter search. The feedback is displayed accurately for the search bar on its own, but not for the search filter. I.e.: if I try to search for jobs created by Microsoft in the search filter and I press on apply search, the search filter closes and I am shown the output of my last search performed through the search bar rather than the filtered search output.

The displaying of the page title and the filter button are dynamic now based on the user's choice

**Review by VCastelli — APPROVED** [review]

**Comment by VCastelli** [comment]
I approve the PR, the functionality works well. I think it could be polished a bit in bug fixes later on.

**Comment by VCastelli** [comment]
I resolved the conflicts that the PR had with main and will merger the PR now.

**Pull request merged**
