### PR TITLE
Job Post Features 

### LINKED ISSUE #116: [US-34] Create a job post
As a registered user, I want to be able to create a job post for an open job position, so that people can view the job posting and apply to it if they choose to.
Note: The job post must consist of the:
- Company name
- Job type (full-time, part-time, internship)
- Job description
- Application submission deadline
- Application submission type (apply in-app or through third-party app - if through third-party app, supply link to job post)

MoSCoW: M
Business Value: XXL
Risk: M

### LINKED ISSUE #117: [US-35] Configure a job post
As a registered user, I want to be able to configure a job post that I’ve created to indicate which documents are mandatory for the posted application (like, resume, cover letter, transcript,...), so that applicants are aware of which documents they must submit for their applications to be considered.

MoSCoW: M
Business Value: XXL
Risk: M

### LINKED ISSUE #119: [US-37] Delete a job post
As a registered user, I want to be able to delete a job post that I have created, so that I can manage my job posts and delete job posts that are no longer relevant.

MoSCoW: M
Business Value: XL
Risk: M

### LINKED ISSUE #134: [US-39] Job Newsfeed
Epic: #77 

As a registered user, I want to be able to view a list of all job posts which I can search through and apply to if I choose.

MoSCoW: M
Business Value:XXL
Risk: M

### PR DESCRIPTION
**Pull request by z-bruce**
Note: If you are testing, upon checking out to this branch, you will need to run `python manage.py migrate` - I did not commit the DB file to avoid conflicts when merging to main.

This pull request includes the implementation of the following user stories: 

- #116 
To test this feature:
  - go to login page
  - sign in to a valid account
  - go to the 'Jobs' page from the Header
  - click 'Create a job'
  - fill out the form
  - press the Save button
  - **Expected Result**: The newly created job post should now be visible on the jobs page.

- #117
To test this feature:
  - go to login page
  - sign in to a valid account
  - go to the 'Jobs' page from the Header
  - either create a new job or edit an existing job
  - from the list, select which documents are required to apply for the job
  - press the Save button
  - **Expected Result**: The job post should now display a "Required Documents" section.

- #118 
To test this feature:
  - go to login page
  - sign in to a valid account
  - go to the 'Jobs' page from the Header
  - after having created at least one Job post, click the edit button on the Job Post
  - modify the form fields as needed
  - press the Save button
  - **Expected Result**: The job post should now display the updated information.

- #134 
To test this feature: 
  - go login page
  - sign in to a valid account
  - click on the 'Jobs' link in the header

If merged, this pull request closes #116, closes #117, closes #119, and closes #134.

### CODE REVIEW

**Review by JIAYI615 — APPROVED** [review]
All changes are reviewed. 
After testing the functions, I failed to find bugs. The mentioned features in this pull request all work fine on my end.
The code is well-commented, both the backend and the frontend code have comments describing the role of the code. The constants and the CSS part are placed in the correct file, the unused file is deleted and the new files are appropriately named. 
I approved this pull request.

**Comment by VCastelli** [comment]
As @JIAYI615 commented, after testing the newly added features, I think that they work well and I haven't been able to find any bugs or problems with them. I think the features are well-implemented and the code is well-documented. Therefore, I approve this PR.

**Review by VCastelli — APPROVED** [review]
As @JIAYI615 commented, after testing the newly added features, I think that they work well and I haven't been able to find any bugs or problems with them. I think the features are well-implemented and the code is well-documented. Therefore, I approve this PR.

**Comment by z-bruce** [comment]
@VCastelli @JIAYI615 Since I pushed one more commit since your initial review, I've just requested another review, if you could take a look when you have a minute. Thanks!

**Review by JIAYI615 — APPROVED** [review]
The newest commit created a page for displaying a single job, therefore it's appropriate to be merged in this pull request. After testing the function, everything works fine on my end. The new code has comments for readability and follows the same coding style. This pull request is approved.

**Review by VCastelli — APPROVED** [review]
I reviewed the PR with the newest commit and my approval for this PR still stands. The features seem to be working well and the code is well-written.

**Pull request merged**
