### PR TITLE
Search for users and bug fixing

### PR DESCRIPTION
**Pull request by Nijaoui-Wassim**
Search for users and bug fixing were implemented
As well as fixing the Job Posts creation and editing to better reflect the user choices

### CODE REVIEW

**Review by haris2055 — APPROVED** [review]
The basic template for the search functionality is working with this pull request. Able to write a name and see the results based on the letters, or characters found in the name or in a certain sequence. I approve these changes but would suggest please ensure there will be no merging conflict with other pull requests.

**Comment by haris2055** [comment]
With Khaled and Victoria working on the search functionality of the backend, it will be reworked and we will merge that once that's been finalized, so this will be saved as a draft in the meantime

**Comment by z-bruce** [comment]
The commit [search functionality](https://github.com/haris2055/SOEN390/pull/155/commits/c98344da1aaffb6caaf6901c533cc41bc9657267) was also present in the UserConnections branch [search functionality](https://github.com/haris2055/SOEN390/pull/160/commits/c98344da1aaffb6caaf6901c533cc41bc9657267) which was already merged to main with PR #160 (User Connections Feature), so the only changes this PR will be making are the updates to Job creation/editing, which are ok to be merged.

**Review by z-bruce — APPROVED** [review]
This PR makes a small fix to the boolean fields Remote/Status for the Job creation/editing features.

**Pull request merged**
