### PR TITLE
Notifications Features

### LINKED ISSUE #126: [US-20] Connection Invitation Notification
Epic: #73 

As a registered user, I want to receive a notification when someone invites me to connect with them, so that I become aware of the invitation.

MoSCoW: M
Business Value:XXL
Risk: L

### LINKED ISSUE #133: [US-27] Legal "Backdoor" Notification
Epic: #74 

As a registered user, I want to be informed that the product includes a legal “backdoor” to identify and/or prevent illegal activities, such as harassment, so that I am aware of my level of privacy.

MoSCoW: M
Business Value: L
Risk: L

### LINKED ISSUE #146: [US-51] Notifications Page
Epic: #79 

As a registered user, I want to be able to view my notifications page which consists of a list of all recent activities (connection invites, activities of users I am connected with (posts & job posts), updates about job posts for which I’ve applied, etc.), so that I can be up to date with relevant system activity.

MoSCoW: M
Business Value:XXL
Risk: M

### LINKED ISSUE #171: [US-42-43-V2] Job Alerts
As a registered user, I want to be able to receive job alerts for newly posted positions that match my specified preferences.

Epic Name: #77 Job Search
MoSCoW: M
Business Value:XL
Risk: M

### PR DESCRIPTION
**Pull request by z-bruce**
This pull request includes the implementation of the following user stories:

#126 [US-20] Connection Invitation Notification
To test this feature:
- Received Connection Request
  - go to login page
  - sign in to a valid account
  - have another user send you a Connection request
  - go to the Notifications page, and there should be a notification which says that you've received a Connection request from that use
-  Sent Connection Request
    - go to login page
    - sign in to a valid account
    - send another user a Connection request
    - have the other user accept the Connection request
    - go to the Notification page, and there should be a notification which says that the other user has accepted your Connection request  

#133 [US-27] Legal "Backdoor" Notification
To test this feature:
- go to register page
- register for a new account
- accept the confirmation email
- log in to your new account
- go to the Notification page, and there should be a notification describing the legal backdoor policy

#171 [US-42-43-V2] Job Alerts
To test this feature:
- Saving Job Alerts
  - go to login page
  - sign in to a valid account
  - navigate to the Job tab of the search results
  - press the Filter button to open the Search Filter form
  - fill out some values into the Fitler Form that you want your Job Alert to be based on
  - press the Save Search button to save the your Search Filter as a Job Alert
  - create a Job that matches the parameters you saved
  - you should receive a notification that a Job has been posted that matches one of your saved Job Alerts

- Managing Job Alerts:
  - in the header, click the Profile drop down menu and click Settings
  - if you have saved any searches as Job Alerts, they should appear below the Forgot Password form
  - try deleting some of your existing Job Alerts

#146 [US-51] Notifications Page
To test this feature:
- try receiving Connection requests and have other users accept your Connection requests
  - try interacting with the Connection request (accept/reject) via the dropdown menu on the notification card
- try receiving Recommendations from other users
  - try viewing the profile of the user who recommended you via the dropdown menu on the notification card
- try saving Job Alerts and have Jobs posted that match any of your saved Job Alerts
  - try viewing the job via the dropdown menu on the notification card
- unread Notification count in Header should update automatically
- when on the Notifications page, Notifications should update automatically 

If merged, this pull request closes #126, closes #133, closes #171, and closes #146.

### CODE REVIEW

**Review by VCastelli — CHANGES_REQUESTED** [review]
I tested all the features for this PR and everything seems to be working well. 

The code seems to be well-documented and the features work well. 

The only issue I notice is that when I first log in through an account, the notifications option in the navbar does not initially appear in the logged-in user's navbar. However, when I refresh the page, it appears in the navbar. I think we should look into a way to correct this behaviour. 

Aside from that issue, I approve the changes made in this pull request.

**Comment by z-bruce** [comment]
> I tested all the features for this PR and everything seems to be working well.
> 
> The code seems to be well-documented and the features work well.
> 
> The only issue I notice is that when I first log in through an account, the notifications option in the navbar does not initially appear in the logged-in user's navbar. However, when I refresh the page, it appears in the navbar. I think we should look into a way to correct this behaviour.
> 
> Aside from that issue, I approve the changes made in this pull request.

Thanks for the review @VCastelli, I'll look into the cause of that issue today.

**Comment by z-bruce** [comment]
Hey @VCastelli, I just pushed a commit which should fix the issue that you mentioned. Please check it out when you have a chance.

**Review by VCastelli — APPROVED** [review]
@z-bruce Looks good! The issue is fixed. 

I approve this PR :) 

Great work!

**Pull request merged**
