### PR TITLE
User Connections Feature

### LINKED ISSUE #88: [US-7] See my list of connections
Epic: #72 

As a registered user, I want to be able to access my list of connections from my user profile, so that I and other users can see who I am connected with.

MoSCoW: M
Business Value:XXL 
Risk: L

### LINKED ISSUE #123: [US-17] Connection Invite
Epic: #73 

As a registered user, I want to invite other users to join my network / connect with me, so that I can grow my list of connections and get to know other users.

MoSCoW: M
Business Value:XXL
Risk: L

### LINKED ISSUE #124: [US-18] Respond to Connection Invites
Epic: #73 

As a registered user, I want to respond to another user’s connection invitation (accept/reject), so that I can expand and manage my list of connections. 

MoSCoW: M
Business Value:XXL
Risk: L

### LINKED ISSUE #125: [US-19] Disconnect From a User
Epic: #73 

As a registered user, I want to be able to sever a connection between my account and that of another user (without notifying that user), so that I can manage and control my list of connections.

MoSCoW: M
Business Value:XXL
Risk: L

### PR DESCRIPTION
**Pull request by z-bruce**
This pull request implements the following features related to #73 [EPIC-3] Connections:
- users can view a list of their connections (accepted connections, as well as pending sent/received connection requests)
- users can send connection invites to other users
- users can respond to connection invites (accept, reject)
- users can disconnect from other users they are connected to, and cancel their pending sent connection requests

closes #88 [US-7] See My List of Connections
closes #123 [US-17] Connection Invite
closes #124 [US-18] Respond to Connection Invite
closes #125 [US-19] Disconnect From a User

### CODE REVIEW

**Comment by z-bruce** [comment]
I will be pushing a commit to resolve this merge conflict. This can be done by replacing the following .pyc files in the UserConnections branch with the versions from the main branch, as these files are inconsequential and regenerated whenever someone runs the code on their own machine. 

Screen Shot 2023-03-25 at 18 38 27

Note, as a code management measure to prevent this type of merge conflict from happening again, I strongly believe the following should be done:
- remove all __pycache__ directories from the repository
- add .pyc files, __pyache__ directories, etc. to the .gitignore file, so the repository does not attempt to track them

I will be creating an issue for this code management suggestion.

**Comment by z-bruce** [comment]
@haris2055 @VCastelli The merge conflicts have been resolved, so this PR is ready for your review whenever you have a chance. Thanks!

**Comment by VCastelli** [comment]
I tested the functionalities mentioned in your pull request description. At the moment, I can see that everything works well. As a user, I can correctly view my list of connections, send connection invites to other users, respond to connection invites and disconnect from other users that I am connected to.

Two points I would like to discuss before accepting this pull request are: 
1. Are users allowed to resend a user a connection request after the first one has been declined? I'm asking, because at the moment it is not possible, so I want to ensure that this is because of a design decision that was taken and that it is not a bug.
2. I think there should be a bit of extra feedback implemented for certain functionalities if possible, such as adding a "are you sure you want to disconnect from this user" message when a user tries to disconnect from a user?

**Comment by JIAYI615** [comment]
For point 1, I tried the function and after the first one was rejected the record in the database was deleted too, it works fine on my side.
For point 2,  it will be good to have an extra safety function. I think we can implement that if we still have time after all the main Epic stories are done

**Comment by VCastelli** [comment]
> For point 1, I tried the function and after the first one was rejected the record in the database was deleted too, it works fine on my side.

Never mind my first point. I tried it again and it works. I think I did something wrong on my end.

**Comment by VCastelli** [comment]
So other than the fact that I feel that the feature should include some added safety messages, I accept the pull request and feel that it is ready to be merged into main. :)

**Comment by z-bruce** [comment]
> So other than the fact that I feel that the feature should include some added safety messages, I accept the pull request and feel that it is ready to be merged into main. :)

Thanks for your review. Moving forward, we can implement a confirmation message before those types of actions (delete, cancel) as an enhancement.

**Review by VCastelli — APPROVED** [review]
My comments have already been written above. But I'll reiterate them here. 

As I see every functionality listed in the PR description works correctly, I approve this PR.

**Review by haris2055 — APPROVED** [review]
Everything works fine with me as well, and all the functionalities mentioned are now functional.

**Comment by JIAYI615** [comment]
Since both reviewers approved this pull request, this branch is ready to be merged into the main branch.

**Pull request merged**
