### PR TITLE
Refactored and redesigned navbar component

### PR DESCRIPTION
**Pull request by VCastelli**
Refactored code for navbar and restyled it. 

To test: 
- click through the various links in the navbar to ensure that all sections of the navbar are correctly linked to their corresponding pages
- make sure that the correct navbar headers appear when the user is logged in vs when the user is logged out

### CODE REVIEW

**Comment by JIAYI615** [comment]
After testing the changes:
1. All the links in navbar work fine
2. Before the user logs in, there are links to the Home, Job, and the login page. After the user logs in, all the links are visible to the user.
All the new CSS code follows the naming style. One thing detected: In Header.js line 128, 'classname' should be 'className'

**Comment by VCastelli** [comment]
> 
Thanks for catching that! Made the necessary edit. I think it's good to go now

**Review by JIAYI615 — APPROVED** [review]
I think everything is fine now. I approved this pull request

**Review by z-bruce — APPROVED** [review]
Links in the header appear as expected when not logged in and when logged in. All links direct to the correct location, and styling is noticeably improved.

**Pull request merged**
