### PR TITLE
Job Applications and Post Interactions

### LINKED ISSUE #78: [EPIC-8] Job Application

### LINKED ISSUE #139: [US-44] Upload and Save Resume and Cover Letter
Epic: #78 

As a registered user, I want to upload and save my resume and cover letter so that I can then use them to easily apply for a job later on.

MoSCoW: M
Business Value:XL
Risk: M

### LINKED ISSUE #140: [US-45] Re-upload and Save Resume and/or Cover Letter
Epic: #78 

As a registered user, I want to be able to re-upload and exchange the stored resume and/or cover letter so that I can keep my profile up to date.

MoSCoW: M
Business Value:XL
Risk: M

### LINKED ISSUE #141: [US-46] Apply In-App or Through Third-Party App Notice
Epic: #78 

As a registered user, I want to know or see if I can apply for a position in a job post through using the system itself, or if I must submit my application through a third-party application.

MoSCoW: M
Business Value:XXL
Risk: M

### LINKED ISSUE #143: [US-48] Apply for a Position Manually
Epic: #78 

As a registered user, I want to be able to manually apply for a position described in a job post by providing the required personal information and uploading my resume and/or cover letter so that the recruiter can receive my application.

MoSCoW: M
Business Value:XXL
Risk: M

### LINKED ISSUE #144: [US-49] Apply for a Position Using Autofill
Epic: #78 

As a registered user, I want to be able to apply for a position described in a job post by having the system automatically provide the recruiter with the required personal information, the saved resume, and the saved cover letter (if needed), so that I can easily submit my job application to the recruiter to be reviewed.

MoSCoW: M
Business Value:XXL
Risk: M

### LINKED ISSUE #145: [US-50] Job Application Review
Epic: #78 

As a registered user, I want to view and review all job applications submitted in response to one of my job posts.

MoSCoW: M
Business Value: L 
Risk: L

### LINKED ISSUE #183: Enhancement [EPIC-5]: Post Interactions
This enhancement to #75 [EPIC-5] Posts will include the following additional features:
- Post Comments
  - Other users who you are connected to may comment on your Posts.
  - You may comment on your own Posts.  
  - You should receive a Notification when another User comments on one of your Posts.
- Post Likes
  - Other users who you are connected to may 'like' your Posts.  
  - You may like your own Posts.
  - You should receive a Notification when another User likes one of your Posts.

### LINKED ISSUE #186: Maintenance: Post images
On the Post newsfeed, the Post image is displayed in a small circle next to the user name. The user's profile image should be displayed in this space, and the Post image should be below the Post content, taking up the full width of the Post card.

Additionally, an image upload field must be added to the Edit Post Form.

### LINKED ISSUE #187: Bug: [US-44] profile file upload refreshing
Noted by @JIAYI615 in PR Review for #185: 

> [US-44]: After the user uploads the files, if the user reopens the form, the uploaded files won't appear in the form, the user needs to refresh the page and then open the form to see their files.

### LINKED ISSUE #188: Bug [US-48][US-49] Other documents upload fails
As noted by @JIAYI615 in PR Review for #185: 

> [US-49][US-48]` If the user chose to upload files to the field 'Other documents', the uploading failed.

### PR DESCRIPTION
**Pull request by z-bruce**
This pull request includes the implementation of user stories featured in #78 [EPIC-8 Job Application], as well as #183 Enhancement [EPIC-5] Post Interactions, and UI styling updates across the entire application.

Features from #78 [EPIC-8 Job Application]:
***
- #139 [US-44] Upload and Save Resume and Cover Letter:
	- sign in to a valid account
	- navigate to My Profile from the header
	- press the Upload Documents button
	- upload a resume and/or cover letter
	- exit the form and press Upload Documents again
	- verify that your document(s) have been saved and you are able to download/view them
***
- #140 [US-45] Re-upload and Save Resume and/or Cover Letter
	- sign in to a valid account
	- navigate to My Profile from the header
	- after having already uploaded documents, press the Upload Documents button
	- try pressing the button to remove either your stored resume or cover letter
	- try re-uploading new documents
	- exit the form, and press the Upload Documents button again to verify that your changes have been saved
***
- #141 [US-46] Apply In-App or Through Third-Party App Notice
	- sign in to a valid account
	- navigate to the Jobs page from the header
	- for an 'internal' Job posting, try pressing the Apply button
		- you should be redirected to the Job Application form
	- for an 'external' Job posting, try pressing the Apply Externally button on the Job post
		- you should be redirected to the website specified by the poster of the Job
***
- #143 [US-48] Apply for a Position Manually
	- sign in to a valid account
	- press the 'Apply' button on a Job on the Jobs page
	- fill out all fields of the Job Application form, and using the file inputs, select documents to upload for each of the specified Required Documents
	- verify that you have filled out the form correctly, and press the Submit button
	- a confirmation message should be displayed stating that your Application was successfully submitted
	- you should receive a notification, stating that you have submitted an Application for the Job
***
- #144 [US-49] Apply for a Position Using Autofill
	- sign in to a valid account
	- fill out your Profile information, and upload a Resume and/or Cover Letter from your Profile page
	- press the 'Apply' button on a Job on the Jobs page
	- on the Job Application form, press the 'Autofill' button
	- your profile information should automatically populate the input fields of the Application form
	- if you uploaded a Resume and/or Cover Letter from your profile page, these should appear
	- you can replace the autofilled Resume and Cover Letter fields with a new file specifically for this Job Application
	- verify that you have filled out the form correctly, and press the Submit button
	- a confirmation message should be displayed stating that your Application was successfully submitted
	- you should receive a notification, stating that you have submitted an Application for the Job
***
- #145 [US-50] Job Application Review
	- sign in to a valid account
	- post a Job listing, and have one or more other users submit Applications for the Job
	- from your Profile page, scroll to the bottom to the 'Your Job Posts' section
		- here, you should see the Job you posted
	- press the 'Review Applications' button next to the Job
		- from the next page, you can view all Applications submitted for the job
	- press 'View Application Detail' to view the user's full Application
	- press 'Remove This Application' to discard the user's Application
***
***
- #183 Enhancement [EPIC-5] Post Interactions:
	- sign in to a valid account
	- have confirmed connections to other users
	- have other user(s) create one or more Posts
	- create one or more of your own Posts
	- from your Posts Newsfeed, try pressing the 'Like' button beneath each of the Posts
		- after Liking a Post, the 'Like' button should turn into an 'Unlike' button and the displayed Like count should update accordingly
		- you should receive a Notification if another user Likes one of your Posts
	- from your Posts Newsfeed, try typing a Comment and press the 'Comment' button
		- the Comments section below the Post content should update instantly with your new Comment
		- you should receive a Notification if another user Comments on one of your Posts
***
***
- UI Updates: 
	- verify that styling is consistent across pages
***
Merging this Pull Request closes #78, closes #139, closes #140, closes #141, closes #143, closes #144, closes #145, closes #183, closes #186, closes #187, closes #188.

### CODE REVIEW

**Comment by JIAYI615** [comment]
Features:
  After trying the features, problems found:
      [US-44]: After the user uploads the files, if the user reopens the form, the uploaded files won't appear in the form, the 
  user needs to refresh the page and then open the form to see their files.
      [US-49][US-48] If the user chose to upload files to the field 'Other documents', the uploading failed.
  All the other features work perfectly.
Styles:
  All the pages have consistent styles: with the same font style, same background color, same button design, etc.
Codes:
  The CSS code has separate files instead of inline styling, the constants and functions are placed in the right places, and the code is well-commented.

**Review by JIAYI615 — COMMENTED** [review]
All file changes for now are reviewed

**Comment by z-bruce** [comment]
@JIAYI615 I have pushed additional commits that correct the issues you mentioned.

**Review by JIAYI615 — APPROVED** [review]
The problems found are fixed now, I failed to find more bugs, therefore I approved this pull request.

**Comment by z-bruce** [comment]
The PR was approved, so it will be merged and the linked User Stories, Enhancements and Bug Reports will be closed.

**Pull request merged**
